__package_name__ = "juno_assembly_verification"
__authors__ = "Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.0.1"
__description__ = "Juno-assembly verification pipeline, used to verifyh updates in Juno-assembly"